### PR TITLE
feat(footer): create custom footer

### PR DESCRIPTION
**Pull request by dnsos**
This PR creates our custom footer for Docusaurus. Some elements (credits, socials, legal links) are configurable via the `docusaurus.config.js`. The logos are hard-coded because they're highly unlikely to change, so we are not making them dynamic for now.

**Note that Tailwind's preflight is enabled with this PR, so we might need to fix some basic styles along the way.**

### CODE REVIEW

**Review by vogelino — CHANGES_REQUESTED** [review]
That's really awesome. So clean and well split in multiple dedicated files! Well done! 😗 👌 

I just noticed that on narrow mobiles the logos don't break to the next line or reduce their size which leads to an horizontal overflow:
image

**Comment by dnsos** [comment]
Good catch! I have fixed this with the last commits.

**Comment by vogelino** [comment]
> Good catch! I have fixed this with the last commits.

Great thx! I noticed I still have an overflow with the links in the bottom:

CleanShot 2023-01-25 at 13 28 34

**Comment by dnsos** [comment]
Uff, thanks! _Now_ it should work 😄

**Review by vogelino — APPROVED** [review]

**Pull request merged**
